version: "3.9"

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
